### PR TITLE
:sparkles: NASA node

### PR DESCRIPTION
**Pull request by ivov**
Hey! This is the NASA node for: https://api.nasa.gov/

Ran tests and linter successfully.

---

What I'm most interested in:

- This node has 19 resources with 1 or at most 2 operations each. Does it make sense to refactor this into 19 `ResourceDescription.ts` files? I couldn't find a node in the codebase to use as a template for a node like this - usually there are few resources with many operations.

- A few fields like `startDate` and `endDate` are duplicated because, if a resource requires shared fields along with non-shared fields inside its `additionalFields`, using shared fields together with non-shared fields results in _two_ instances of `additionalFields` instead of only one. Is there a way to avoid this duplication without cluttering up the UI?

---

Notes on resources:

1. `astronomyPictureOfTheDay`
`date` defaults to today

2. `asteroidNeoFeed
`
`startDate` and `endDate` default to today.
The request date range is limited by NASA to 7 days. 
Example test values: `startDate` 2015-09-07 → `endDate` 2015-09-08

3. `asteroidNeoLookup`
Example test value: 3542519

4. `asteroidNeoBrowse`
No notes needed.

5. (up to 14) `donki-` resources
`startDate` defaults to thirty days before today, except in`donkiWsaEnlilSimulation` and `donkiNotifications`, where it defaults to 7 days before today.
`endDate` defaults to today.
The request date range is limited by NASA to 30 days.
Example test values: `startDate` 2016-09-01 → `endDate` 2016-09-30
With the `donki-` resources it is sometimes difficult to get back results when inputting values at random. If they resources are not returning any results, you can look at the NASA API entry for example values that give back results.

`donki-` resource list:
- `donkiCoronalMassEjection`
- `donkiGeomagneticStorm`
- `donkiInterplanetaryShock`
- `donkiSolarFlare`
- `donkiSolarEnergeticParticle`
- `donkiMagnetopauseCrossing`
- `donkiRadiationBeltEnhancement`
- `donkiHighSpeedStream`
- `donkiWsaEnlilSimulation`
- `donkiNotifications`

15. `earthImagery`
`date` defaults to date of most recent image
Example test values: 
`lat` 29.78
`lon` -95.33
`dim` (degrees) 0.15
`date` 2018-01-01

16. `earthAssets`
Example test values: Same as 15 above.

17. `inSightMarsWeatherService`
No notes needed.

18. `marsRoverPhotos`
A "sol" is a Martian day, longer than ours, counted since touchdown.
Example test value: `sol` 1000

19. `techport`
Example test value: `projectId` 17792

### CODE REVIEW

**Review by erin2722 — COMMENTED** [review]
Your code is really nicely written (as usual), so no comments regarding syntax. I messaged you regarding details in node operations, but overall I'd say go through and set default values that make using the different operations more intuitive.

Great job! 🚀

**Comment by ivov** [comment]
To fix per @erin2722's review:
- `returnAll` for `getAll` for `asteroidNeoBrowse` fails
- Return empty object when no result
- Make lat/long decimal instead of integer (if possible)
- Change default `sol` value for `marsRoverPhotos`
- Clean up error messages
- Clean up table

**Review by Shraddha2104 — COMMENTED** [review]
Hey @ivov,
I just had a look at it.
The code looks really awesome in terms of functionalities.
Maybe, you could make the code a bit cleaner by separating the operations and fields for each resource in different files.
I found this convention for a lot of large nodes.

Awesome work! ✨

**Comment by ivov** [comment]
Thanks @Shraddha2104! Exactly, that's what I was asking about in the top post, do you think it's worth it to have 19 separate files instead of one big file? Because these are a lot of resources with only a few operations each, unlike most other nodes where there are few resources with many operations each.

**Comment by ivov** [comment]
About `returnAll`, it's now fixed, but bear in mind that it takes about a minute or so to retrieve everything.

About the defaults, I changed a few, but there are many resources where the default is simply the one set by NASA. Since those defaults are often a 30-day range ending on the current date, since many of the events recorded are rare, it's likely that the API default will return nothing. I agree that the defaults look unintuitive, but maybe NASA expects the user to know what they're looking for.

About changing `lat` and `lon` from `number` to `float`, I looked into this and `type` only allows for `NodePropertyTypes`, which only includes `number`. This would be a change to core functionality, perhaps outside the scope of a node PR.

```ts
export declare type NodePropertyTypes = 'boolean' | 'collection' | 'color' | 'dateTime' | 'fixedCollection' | 'hidden' | 'json' | 'multiOptions' | 'number' | 'options' | 'string';
```

About the table, I cleaned up `techPort` but in `asteroidNeoFeed` I think the structure is correct, even if it's a lot of data for one of the cells in the row.

I'll ask the maintainers about refactoring this into 19 separate resources, before going forward with it.

**Pull request closed without merging**
